// mutations函数操作定义

//画布相关
export const INIT_GRAPH = 'INIT_GRAPH'
export const ZOOM_GRAPH = 'ZOOM_GRAPH'
export const POSITIONING_GRAPH = 'POSITIONING_GRAPH'
export const UNDO_GRAPH = 'UNDO_GRAPH'
export const REDO_GRAPH = 'REDO_GRAPH'
export const STORAGE_GRAPH = 'STORAGE_GRAPH'
export const LOAD_GRAPH = 'LOAD_GRAPH'
export const MODIFY_GRAPH = "MODIFY_GRAPH"
export const CLEAR_GRAPH = "CLEAR_GRAPH"
export const MODIFY_CONFIGDATA = "MODIFY_CONFIGDATA"
export const LOAD_CONFIGDATA = "LOAD_CONFIGDATA"
//模型上传  TODO移除该部分相关内容
export const SHOW_UPLOAD_DIALOG = "SHOW_UPLOAD_DIALOG"
export const CLOSE_UPLOAD_DIALOG = "CLOSE_UPLOAD_DIALOG"

//测算相关
export const LOAD_HISTORY_SIMULATE_DATA = "LOAD_HISTORY_SIMULATE_DATA"
export const MODIFY_HISTORY_SIMULATE_DATA = "MODIFY_HISTORY_SIMULATE_DATA"
export const APPEND_HISTORY_SIMULATE_DATA = "APPEND_HISTORY_SIMULATE_DATA"
export const SET_HISTORY_SIMULATE_DATA = "SET_HISTORY_SIMULATE_DATA"
// 设置测算次数
export const SET_NONCE = "SET_NONCE";
// 设置测算模型对象的实例
export const SET_MODEL = "SET_MODEL"
export const REMOVE_CELLS = "REMOVE_CELLS"
export const SET_EDIT_CELLS = "SET_EDIT_CELLS"


//WEB3相关
export const SET_WEB3_PROVIDER = "SET_WEB3_PROVIDER"
export const SET_USER = "SET_USER"


export const SET_EDIT_RULE = "SET_EDIT_RULE"
export const SAVE_EDIT_RULE = "SAVE_EDIT_RULE"
export const LOAD_RULE_LISTS = "LOAD_RULE_LISTS"

